// Mocks generated by Mockito 5.4.6 from annotations
// in core_domain/test/domain/usecases/save_transcript_segment_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core_domain/domain/entities/transcript_segment.entity.dart'
    as _i2;
import 'package:core_domain/domain/repositories/transcript.repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTranscriptSegmentEntity_0 extends _i1.SmartFake
    implements _i2.TranscriptSegmentEntity {
  _FakeTranscriptSegmentEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TranscriptRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranscriptRepository extends _i1.Mock
    implements _i3.TranscriptRepository {
  MockTranscriptRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TranscriptSegmentEntity>> getBySessionId(
    String? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBySessionId, [sessionId]),
            returnValue: _i4.Future<List<_i2.TranscriptSegmentEntity>>.value(
              <_i2.TranscriptSegmentEntity>[],
            ),
          )
          as _i4.Future<List<_i2.TranscriptSegmentEntity>>);

  @override
  _i4.Future<_i2.TranscriptSegmentEntity> save(
    _i2.TranscriptSegmentEntity? segment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#save, [segment]),
            returnValue: _i4.Future<_i2.TranscriptSegmentEntity>.value(
              _FakeTranscriptSegmentEntity_0(
                this,
                Invocation.method(#save, [segment]),
              ),
            ),
          )
          as _i4.Future<_i2.TranscriptSegmentEntity>);

  @override
  _i4.Future<List<_i2.TranscriptSegmentEntity>> saveBatch(
    List<_i2.TranscriptSegmentEntity>? segments,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveBatch, [segments]),
            returnValue: _i4.Future<List<_i2.TranscriptSegmentEntity>>.value(
              <_i2.TranscriptSegmentEntity>[],
            ),
          )
          as _i4.Future<List<_i2.TranscriptSegmentEntity>>);

  @override
  _i4.Future<void> deleteBySessionId(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBySessionId, [sessionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
