// Mocks generated by Mockito 5.4.6 from annotations
// in core_domain/test/domain/usecases/start_session_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core_domain/domain/entities/session.entity.dart' as _i2;
import 'package:core_domain/domain/repositories/session.repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSessionEntity_0 extends _i1.SmartFake implements _i2.SessionEntity {
  _FakeSessionEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i3.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.SessionEntity>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i2.SessionEntity>>.value(
              <_i2.SessionEntity>[],
            ),
          )
          as _i4.Future<List<_i2.SessionEntity>>);

  @override
  _i4.Future<_i2.SessionEntity?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i2.SessionEntity?>.value(),
          )
          as _i4.Future<_i2.SessionEntity?>);

  @override
  _i4.Future<_i2.SessionEntity> create(_i2.SessionEntity? session) =>
      (super.noSuchMethod(
            Invocation.method(#create, [session]),
            returnValue: _i4.Future<_i2.SessionEntity>.value(
              _FakeSessionEntity_0(this, Invocation.method(#create, [session])),
            ),
          )
          as _i4.Future<_i2.SessionEntity>);

  @override
  _i4.Future<_i2.SessionEntity> update(_i2.SessionEntity? session) =>
      (super.noSuchMethod(
            Invocation.method(#update, [session]),
            returnValue: _i4.Future<_i2.SessionEntity>.value(
              _FakeSessionEntity_0(this, Invocation.method(#update, [session])),
            ),
          )
          as _i4.Future<_i2.SessionEntity>);

  @override
  _i4.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i2.SessionEntity>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i4.Stream<List<_i2.SessionEntity>>.empty(),
          )
          as _i4.Stream<List<_i2.SessionEntity>>);
}
