// Mocks generated by Mockito 5.4.6 from annotations
// in core_data/test/repositories/session_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:core_data/datasources/local/session.local.data_source.dart'
    as _i2;
import 'package:core_data/model/local/session.local.model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SessionLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionLocalDataSource extends _i1.Mock
    implements _i2.SessionLocalDataSource {
  MockSessionLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.SessionLocalModel>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i4.SessionLocalModel>>.value(
              <_i4.SessionLocalModel>[],
            ),
          )
          as _i3.Future<List<_i4.SessionLocalModel>>);

  @override
  _i3.Future<_i4.SessionLocalModel?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.SessionLocalModel?>.value(),
          )
          as _i3.Future<_i4.SessionLocalModel?>);

  @override
  _i3.Future<void> insert(_i4.SessionLocalModel? session) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [session]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i4.SessionLocalModel? session) =>
      (super.noSuchMethod(
            Invocation.method(#update, [session]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.SessionLocalModel>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i4.SessionLocalModel>>.empty(),
          )
          as _i3.Stream<List<_i4.SessionLocalModel>>);
}
