// Mocks generated by Mockito 5.4.6 from annotations
// in core_data/test/repositories/transcript_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:core_data/datasources/local/transcript.local.data_source.dart'
    as _i2;
import 'package:core_data/model/local/transcript_segment.local.model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TranscriptLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranscriptLocalDataSource extends _i1.Mock
    implements _i2.TranscriptLocalDataSource {
  MockTranscriptLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TranscriptSegmentLocalModel>> getBySessionId(
    String? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBySessionId, [sessionId]),
            returnValue:
                _i3.Future<List<_i4.TranscriptSegmentLocalModel>>.value(
                  <_i4.TranscriptSegmentLocalModel>[],
                ),
          )
          as _i3.Future<List<_i4.TranscriptSegmentLocalModel>>);

  @override
  _i3.Future<void> insert(_i4.TranscriptSegmentLocalModel? segment) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [segment]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertBatch(
    List<_i4.TranscriptSegmentLocalModel>? segments,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertBatch, [segments]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBySessionId(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBySessionId, [sessionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.TranscriptSegmentLocalModel>> watchBySessionId(
    String? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchBySessionId, [sessionId]),
            returnValue:
                _i3.Stream<List<_i4.TranscriptSegmentLocalModel>>.empty(),
          )
          as _i3.Stream<List<_i4.TranscriptSegmentLocalModel>>);
}
